// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Order struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	CouponCode     pgtype.Text        `db:"coupon_code" json:"coupon_code"`
	TotalAmount    decimal.Decimal    `db:"total_amount" json:"total_amount"`
	DiscountAmount decimal.Decimal    `db:"discount_amount" json:"discount_amount"`
	FinalAmount    decimal.Decimal    `db:"final_amount" json:"final_amount"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrderItem struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	OrderID    uuid.UUID          `db:"order_id" json:"order_id"`
	ProductID  string             `db:"product_id" json:"product_id"`
	Quantity   int32              `db:"quantity" json:"quantity"`
	UnitPrice  decimal.Decimal    `db:"unit_price" json:"unit_price"`
	TotalPrice decimal.Decimal    `db:"total_price" json:"total_price"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
