// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: coupon_order.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkCouponUsageInOrder = `-- name: CheckCouponUsageInOrder :one
SELECT EXISTS(
    SELECT 1 FROM coupon_order
    WHERE order_id = $1 AND coupon_id = $2
) as exists
`

type CheckCouponUsageInOrderParams struct {
	OrderID  uuid.UUID `db:"order_id" json:"order_id"`
	CouponID uuid.UUID `db:"coupon_id" json:"coupon_id"`
}

func (q *Queries) CheckCouponUsageInOrder(ctx context.Context, arg CheckCouponUsageInOrderParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCouponUsageInOrder, arg.OrderID, arg.CouponID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCouponOrders = `-- name: CountCouponOrders :one
SELECT COUNT(*) FROM coupon_order
`

func (q *Queries) CountCouponOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCouponOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCouponOrdersByCouponID = `-- name: CountCouponOrdersByCouponID :one
SELECT COUNT(*) FROM coupon_order
WHERE coupon_id = $1
`

func (q *Queries) CountCouponOrdersByCouponID(ctx context.Context, couponID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCouponOrdersByCouponID, couponID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCouponOrdersByOrderID = `-- name: CountCouponOrdersByOrderID :one
SELECT COUNT(*) FROM coupon_order
WHERE order_id = $1
`

func (q *Queries) CountCouponOrdersByOrderID(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCouponOrdersByOrderID, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCouponOrder = `-- name: CreateCouponOrder :one
INSERT INTO coupon_order (
    order_id,
    coupon_id
) VALUES (
    $1, $2
) RETURNING id, order_id, coupon_id, created_at, updated_at
`

type CreateCouponOrderParams struct {
	OrderID  uuid.UUID `db:"order_id" json:"order_id"`
	CouponID uuid.UUID `db:"coupon_id" json:"coupon_id"`
}

func (q *Queries) CreateCouponOrder(ctx context.Context, arg CreateCouponOrderParams) (CouponOrder, error) {
	row := q.db.QueryRow(ctx, createCouponOrder, arg.OrderID, arg.CouponID)
	var i CouponOrder
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CouponID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCouponOrder = `-- name: DeleteCouponOrder :exec
DELETE FROM coupon_order
WHERE id = $1
`

func (q *Queries) DeleteCouponOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCouponOrder, id)
	return err
}

const deleteCouponOrderByCouponID = `-- name: DeleteCouponOrderByCouponID :exec
DELETE FROM coupon_order
WHERE coupon_id = $1
`

func (q *Queries) DeleteCouponOrderByCouponID(ctx context.Context, couponID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCouponOrderByCouponID, couponID)
	return err
}

const deleteCouponOrderByOrderID = `-- name: DeleteCouponOrderByOrderID :exec
DELETE FROM coupon_order
WHERE order_id = $1
`

func (q *Queries) DeleteCouponOrderByOrderID(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCouponOrderByOrderID, orderID)
	return err
}

const getCouponOrder = `-- name: GetCouponOrder :one
SELECT id, order_id, coupon_id, created_at, updated_at FROM coupon_order
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCouponOrder(ctx context.Context, id uuid.UUID) (CouponOrder, error) {
	row := q.db.QueryRow(ctx, getCouponOrder, id)
	var i CouponOrder
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CouponID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponOrderByCouponID = `-- name: GetCouponOrderByCouponID :many
SELECT id, order_id, coupon_id, created_at, updated_at FROM coupon_order
WHERE coupon_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCouponOrderByCouponID(ctx context.Context, couponID uuid.UUID) ([]CouponOrder, error) {
	rows, err := q.db.Query(ctx, getCouponOrderByCouponID, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CouponOrder{}
	for rows.Next() {
		var i CouponOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CouponID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCouponOrderByOrderAndCoupon = `-- name: GetCouponOrderByOrderAndCoupon :one
SELECT id, order_id, coupon_id, created_at, updated_at FROM coupon_order
WHERE order_id = $1 AND coupon_id = $2
LIMIT 1
`

type GetCouponOrderByOrderAndCouponParams struct {
	OrderID  uuid.UUID `db:"order_id" json:"order_id"`
	CouponID uuid.UUID `db:"coupon_id" json:"coupon_id"`
}

func (q *Queries) GetCouponOrderByOrderAndCoupon(ctx context.Context, arg GetCouponOrderByOrderAndCouponParams) (CouponOrder, error) {
	row := q.db.QueryRow(ctx, getCouponOrderByOrderAndCoupon, arg.OrderID, arg.CouponID)
	var i CouponOrder
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CouponID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponOrderByOrderID = `-- name: GetCouponOrderByOrderID :many
SELECT co.id, co.order_id, co.coupon_id, co.created_at, co.updated_at, c.coupon_code, c.is_valid
FROM coupon_order co
JOIN coupons c ON co.coupon_id = c.id
WHERE co.order_id = $1
ORDER BY co.created_at DESC
`

type GetCouponOrderByOrderIDRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	OrderID    uuid.UUID          `db:"order_id" json:"order_id"`
	CouponID   uuid.UUID          `db:"coupon_id" json:"coupon_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CouponCode string             `db:"coupon_code" json:"coupon_code"`
	IsValid    bool               `db:"is_valid" json:"is_valid"`
}

func (q *Queries) GetCouponOrderByOrderID(ctx context.Context, orderID uuid.UUID) ([]GetCouponOrderByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getCouponOrderByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCouponOrderByOrderIDRow{}
	for rows.Next() {
		var i GetCouponOrderByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CouponID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CouponCode,
			&i.IsValid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponOrders = `-- name: ListCouponOrders :many
SELECT co.id, co.order_id, co.coupon_id, co.created_at, co.updated_at, c.coupon_code, c.is_valid
FROM coupon_order co
JOIN coupons c ON co.coupon_id = c.id
ORDER BY co.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCouponOrdersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListCouponOrdersRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	OrderID    uuid.UUID          `db:"order_id" json:"order_id"`
	CouponID   uuid.UUID          `db:"coupon_id" json:"coupon_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CouponCode string             `db:"coupon_code" json:"coupon_code"`
	IsValid    bool               `db:"is_valid" json:"is_valid"`
}

func (q *Queries) ListCouponOrders(ctx context.Context, arg ListCouponOrdersParams) ([]ListCouponOrdersRow, error) {
	rows, err := q.db.Query(ctx, listCouponOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCouponOrdersRow{}
	for rows.Next() {
		var i ListCouponOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CouponID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CouponCode,
			&i.IsValid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCouponOrder = `-- name: UpdateCouponOrder :one
UPDATE coupon_order
SET 
    order_id = $2,
    coupon_id = $3
WHERE id = $1
RETURNING id, order_id, coupon_id, created_at, updated_at
`

type UpdateCouponOrderParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	OrderID  uuid.UUID `db:"order_id" json:"order_id"`
	CouponID uuid.UUID `db:"coupon_id" json:"coupon_id"`
}

func (q *Queries) UpdateCouponOrder(ctx context.Context, arg UpdateCouponOrderParams) (CouponOrder, error) {
	row := q.db.QueryRow(ctx, updateCouponOrder, arg.ID, arg.OrderID, arg.CouponID)
	var i CouponOrder
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CouponID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
