// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: coupons.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCoupons = `-- name: CountCoupons :one
SELECT COUNT(*) FROM coupons
`

func (q *Queries) CountCoupons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCoupons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidCoupons = `-- name: CountValidCoupons :one
SELECT COUNT(*) FROM coupons
WHERE is_valid = true
`

func (q *Queries) CountValidCoupons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countValidCoupons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    coupon_code,
    is_valid
) VALUES (
    $1, $2
) RETURNING id, coupon_code, is_valid, created_at, updated_at
`

type CreateCouponParams struct {
	CouponCode string `db:"coupon_code" json:"coupon_code"`
	IsValid    bool   `db:"is_valid" json:"is_valid"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon, arg.CouponCode, arg.IsValid)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.IsValid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :exec
DELETE FROM coupons
WHERE id = $1
`

func (q *Queries) DeleteCoupon(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoupon, id)
	return err
}

const getCoupon = `-- name: GetCoupon :one
SELECT id, coupon_code, is_valid, created_at, updated_at FROM coupons
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCoupon(ctx context.Context, id uuid.UUID) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCoupon, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.IsValid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, coupon_code, is_valid, created_at, updated_at FROM coupons
WHERE coupon_code = $1 LIMIT 1
`

func (q *Queries) GetCouponByCode(ctx context.Context, couponCode string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, couponCode)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.IsValid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoupons = `-- name: ListCoupons :many
SELECT id, coupon_code, is_valid, created_at, updated_at FROM coupons
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCouponsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCoupons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.CouponCode,
			&i.IsValid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidCoupons = `-- name: ListValidCoupons :many
SELECT id, coupon_code, is_valid, created_at, updated_at FROM coupons
WHERE is_valid = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListValidCouponsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListValidCoupons(ctx context.Context, arg ListValidCouponsParams) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listValidCoupons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.CouponCode,
			&i.IsValid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCouponsByCode = `-- name: SearchCouponsByCode :many
SELECT id, coupon_code, is_valid, created_at, updated_at FROM coupons
WHERE coupon_code ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchCouponsByCodeParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchCouponsByCode(ctx context.Context, arg SearchCouponsByCodeParams) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, searchCouponsByCode, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.CouponCode,
			&i.IsValid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoupon = `-- name: UpdateCoupon :one
UPDATE coupons
SET 
    coupon_code = $2,
    is_valid = $3
WHERE id = $1
RETURNING id, coupon_code, is_valid, created_at, updated_at
`

type UpdateCouponParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	CouponCode string    `db:"coupon_code" json:"coupon_code"`
	IsValid    bool      `db:"is_valid" json:"is_valid"`
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, updateCoupon, arg.ID, arg.CouponCode, arg.IsValid)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.IsValid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCouponValidity = `-- name: UpdateCouponValidity :one
UPDATE coupons
SET is_valid = $2
WHERE id = $1
RETURNING id, coupon_code, is_valid, created_at, updated_at
`

type UpdateCouponValidityParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	IsValid bool      `db:"is_valid" json:"is_valid"`
}

func (q *Queries) UpdateCouponValidity(ctx context.Context, arg UpdateCouponValidityParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, updateCouponValidity, arg.ID, arg.IsValid)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.IsValid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
