// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckCouponUsageInOrder(ctx context.Context, arg CheckCouponUsageInOrderParams) (bool, error)
	CountCouponOrders(ctx context.Context) (int64, error)
	CountCouponOrdersByCouponID(ctx context.Context, couponID uuid.UUID) (int64, error)
	CountCouponOrdersByOrderID(ctx context.Context, orderID uuid.UUID) (int64, error)
	CountCoupons(ctx context.Context) (int64, error)
	CountValidCoupons(ctx context.Context) (int64, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateCouponOrder(ctx context.Context, arg CreateCouponOrderParams) (CouponOrder, error)
	DeleteCoupon(ctx context.Context, id uuid.UUID) error
	DeleteCouponOrder(ctx context.Context, id uuid.UUID) error
	DeleteCouponOrderByCouponID(ctx context.Context, couponID uuid.UUID) error
	DeleteCouponOrderByOrderID(ctx context.Context, orderID uuid.UUID) error
	GetCoupon(ctx context.Context, id uuid.UUID) (Coupon, error)
	GetCouponByCode(ctx context.Context, couponCode string) (Coupon, error)
	GetCouponOrder(ctx context.Context, id uuid.UUID) (CouponOrder, error)
	GetCouponOrderByCouponID(ctx context.Context, couponID uuid.UUID) ([]CouponOrder, error)
	GetCouponOrderByOrderAndCoupon(ctx context.Context, arg GetCouponOrderByOrderAndCouponParams) (CouponOrder, error)
	GetCouponOrderByOrderID(ctx context.Context, orderID uuid.UUID) ([]GetCouponOrderByOrderIDRow, error)
	ListCouponOrders(ctx context.Context, arg ListCouponOrdersParams) ([]ListCouponOrdersRow, error)
	ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error)
	ListValidCoupons(ctx context.Context, arg ListValidCouponsParams) ([]Coupon, error)
	SearchCouponsByCode(ctx context.Context, arg SearchCouponsByCodeParams) ([]Coupon, error)
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error)
	UpdateCouponOrder(ctx context.Context, arg UpdateCouponOrderParams) (CouponOrder, error)
	UpdateCouponValidity(ctx context.Context, arg UpdateCouponValidityParams) (Coupon, error)
}

var _ Querier = (*Queries)(nil)
