// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, price, category FROM products
WHERE id = $1 LIMIT 1
`

type GetProductRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Category pgtype.Text    `json:"category"`
}

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Category,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, category FROM products
ORDER BY name ASC
`

type ListProductsRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Price    pgtype.Numeric `json:"price"`
	Category pgtype.Text    `json:"category"`
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
