// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
}

var _ Querier = (*Queries)(nil)
